version: '3'
services:
  alert-webhook:
    build: . 
    image: alert-webhook
    volumes: 
      - ./temp:/root/temp
      - ./conf.yaml:/root/conf.yaml
    command: " -c /root/conf.yaml"
    ports:
      - "8080:8080"
